---
- name: Upload latest components if available
  hosts: localhost
  tasks:
    - include: refreshpuddles.yml
      with_items: '{{ components }}'
      loop_control:
        loop_var: component_to_upload
